name: backoffice ci
on:
  workflow_dispatch:
  push:
    paths:
      - 'backoffice/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'backoffice/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'    # These apps use Node 18 based on package.json
        cache: 'npm'
        cache-dependency-path: 'backoffice/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./backoffice
      run: npm ci
        
    - name: Build Next.js app
      working-directory: ./backoffice
      run: npm run build