name: product service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'product/**'
      # any pushes to main, matches anything within product recursively
  pull_request:
    branches: [ "main" ]
    paths:
      - 'product/**'
      # any pull requests to main, matches anything within product recursively

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build and Test product Service
      # -pl product: Only build product project
      # -am: Also make dependencies (build common-library if needed)
      run: ./mvnw -B clean verify -pl product -am
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: product-test-results
        path: product/target/surefire-reports/*.xml
