name: webhook CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'webhook/**'
      # any pushes to any, matches anything within cart recursively
  pull_request:
    branches: ["main"]
    paths:
      - 'webhook/**'
      # any pull requests to main, matches anything within cart recursively

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Debug Info
      run: |
        pwd
        ls -la
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PA_TOKEN }}
        
    - name: Build and Test webhook Service
      # -pl webhook: Only build webhook project
      # -am: Also make dependencies (build common-library if needed)
      run: mvn -B clean verify -pl webhook -am # switching to system maven
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: webhook-test-results
        path: webhook/target/surefire-reports/*.xml